// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class xoa_foreignkey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(xoa_foreignkey));
        
        string IMigrationMetadata.Id
        {
            get { return "201807241817377_xoa_foreignkey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
